# Generated by Django 4.0.3 on 2022-03-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='detail',
            new_name='content',
        ),
    ]
